server:
    port: 8081
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: 1234
        url: jdbc:h2:mem:commanddb
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true

    kafka:
        bootstrap-servers: kafka1:9092
        consumer:
            group-id: test-consumer-group
message:
    topic:
        createPhone: create-phone